

# services:
#   flask-app:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - ${PWD}:/app
#     environment:
#       - FLASK_ENV=development
#       - DATABASE_URL=postgresql://martin:test@db:5432/mydatabase
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: martin
#       POSTGRES_PASSWORD: test
#       POSTGRES_DB: mydatabase
#     volumes:
#       - pgdata:/var/lib/postgresql/data
  
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - "8082:8080"

# volumes:
#   pgdata:

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://martin:test@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

volumes:
  pgdata:
